### ISSUE TITLE
Install fails because /usr/local/etc/rc.conf.d does not exist

### ISSUE THREAD

**Issue by o87h** [tschettervictor/truenas-iocage-vaultwarden#3]
On TrueNAS-13.0-U6.1, the Vaultwarden install fails because /usr/local/etc/rc.conf.d does not exist in the jail.

I was able to fix this by adding the following to the script:

iocage exec "${JAIL_NAME}" pkg install -y vaultwarden
**_iocage exec "${JAIL_NAME}" mkdir /usr/local/etc/rc.conf.d_** <- New
iocage exec "${JAIL_NAME}" cp -f /mnt/includes/vaultwarden /usr/local/etc/rc.conf.d/
iocage exec "${JAIL_NAME}" sed -i '' "s/yourhostnamehere/${HOST_NAME}/" /usr/local/etc/rc.conf.d/vaultwarden

Thanks and love your work.

**Comment by tschettervictor** [comment]
Script updated
